<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Problems</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Euler_core\Euler_core.csproj" />
    </ItemGroup>

</Project>
